// Elegance Wear — Product Catalogue (local real product photos)

const SITE_BASE = location.pathname.includes('/categories/') ? '../' : '';
const IMG = (p) => SITE_BASE + p;

const productsData = {
    bridal: [
        { id:'b1',  name:'Ivory Lace Wedding Gown',          category:'Bridal', price:75000,  discount:20, image:'Images/Bridle/22-12.jpg', colors:['#FFFFFF','#F5F5DC','#FDF5E6'], description:'An exquisite bridal masterpiece with intricate lacework and a breathtaking silhouette crafted for the most unforgettable day of your life.' },
        { id:'b2',  name:'Satin Mermaid Gown',               category:'Bridal', price:80000,  discount:20, image:'Images/Bridle/WhatsApp-Image-2022-11-24-at-5.44.38-PM.jpg', colors:['#FFE4E1','#FFFFFF','#F5DEB3'], description:'Luxurious satin mermaid gown with a figure-flattering silhouette and delicate hand-sewn embellishments.' },
        { id:'b3',  name:'Royal Embroidered Lehanga',        category:'Bridal', price:85000,  discount:20, image:'Images/Bridle/RedBridalPishwasLehengaPakistaniBridalDress2023_620x.webp', colors:['#800000','#D4AF37','#FFF8DC'], description:'A majestic lehanga adorned with royal embroidery — a timeless piece for the grandest celebrations.' },
        { id:'b4',  name:'Pearl Off-Shoulder Gown',          category:'Bridal', price:90000,  discount:20, image:'Images/Bridle/Ice-Blue-Bridal-Maxi-47.webp', colors:['#FFFFFF','#F5F5DC','#E8D5B7'], description:'Elegant off-shoulder gown embellished with freshwater pearls and a sweeping train.' },
        { id:'b5',  name:'Classic Ivory Maxi Dress',          category:'Bridal', price:95000,  discount:20, image:'Images/Bridle/Jancember-MN293-Luxury-Light-Blue-Wedding-Dress-3D-Flower-Bridal-Gown-Sparkly-Ball-Gown-Vestido-De-Novia-Romantic-Garden-Party.avif', colors:['#FFFFF0','#FFF8DC','#F5F5DC'], description:'A classic ivory maxi with timeless elegance — pure sophistication for the modern bride.' },
        { id:'b6',  name:'Rose Chiffon Evening Gown',         category:'Bridal', price:78000,  discount:20, image:'Images/Bridle/images%20(1).jpeg', colors:['#FFB6C1','#FFC0CB','#FFFFFF'], description:'Soft rose chiffon layered gown with ethereal movement and a romantic silhouette.' },
        { id:'b7',  name:'Emerald Velvet Gown',               category:'Bridal', price:82000,  discount:20, image:'Images/Bridle/images%20(2).jpeg', colors:['#006400','#228B22','#000000'], description:'Deep emerald velvet gown that commands attention with its rich texture and regal presence.' },
        { id:'b8',  name:'Crystal Beaded Reception Dress',    category:'Bridal', price:88000,  discount:20, image:'Images/Bridle/images%20(3).jpeg', colors:['#C0C0C0','#FFFFFF','#E8E8E8'], description:'Hand-beaded crystal reception dress that sparkles with every step — pure glamour.' },
        { id:'b9',  name:'Blush Tulle Ball Gown',             category:'Bridal', price:92000,  discount:20, image:'Images/Bridle/images%20(4).jpeg', colors:['#FFB6C1','#FFE4E1','#FFFFFF'], description:'Dreamy blush tulle ball gown with voluminous layers and fairy-tale charm.' },
        { id:'b10', name:'Duchess Satin Bridal Gown',         category:'Bridal', price:98000,  discount:20, image:'Images/Bridle/images%20(5).jpeg', colors:['#FFFFF0','#F5F5DC','#FFF8DC'], description:'Duchess satin bridal gown with impeccable structure and a cathedral-length train.' },
        { id:'b11', name:'Ivory Gown With Cape Train',        category:'Bridal', price:102000, discount:20, image:'Images/Bridle/images%20(6).jpeg', colors:['#FFFFFF','#FAF0E6','#F5F5DC'], description:'Modern ivory gown with a dramatic cape train — contemporary bridal luxury.' },
        { id:'b12', name:'Champagne Sequin Party Gown',       category:'Bridal', price:76000,  discount:20, image:'Images/Bridle/images%20(7).jpeg', colors:['#F7E7CE','#FFE4B5','#FFF8DC'], description:'Champagne sequin party gown that catches the light — perfect for post-wedding celebrations.' }
    ],

    casual: [
        { id:'c1',  name:'Floral Midi Dress',          category:'Casual', price:3500,  discount:15, image:'Images/Casual%20Dresses/turbolight-winter-dress-designs-2025-new-arrivals-dhanak-collection-khaddar-velvet-online-end-year-sale-dhanak-dress-design_3927b6e53690d238b3857a4f8995d6fd.jpg', colors:['#ADD8E6','#FFFFFF','#FFE4E1'], description:'Comfortable yet chic floral midi dress, cut from breathable premium fabrics for effortless elegance all day.' },
        { id:'c2',  name:'Linen Co-Ord Set',           category:'Casual', price:3750,  discount:15, image:'Images/Casual%20Dresses/RL661.webp', colors:['#F5F5F5','#D3D3D3','#FFB6C1'], description:'Relaxed linen co-ord set with modern tailoring — the ultimate off-duty look.' },
        { id:'c3',  name:'Embroidered Kurta Set',      category:'Casual', price:4000,  discount:15, image:'Images/Casual%20Dresses/p16912-embroidered-lawn-dress_1b574fc4-aa42-4f47-96fe-439a67fc7fcc_580x.webp', colors:['#000000','#D4AF37','#FFFFFF'], description:'Beautifully embroidered kurta set blending traditional artistry with modern silhouettes.' },
        { id:'c4',  name:'Wide-Leg Trouser Set',       category:'Casual', price:4250,  discount:15, image:'Images/Casual%20Dresses/MARIA_B_EID_LAWN_COLLECTION_24_MBEC_03.webp', colors:['#2F4F4F','#000000','#FFFFFF'], description:'Sharp wide-leg trouser set with a relaxed blazer — boardroom to brunch in one look.' },
        { id:'c5',  name:'Blazer Set',                  category:'Casual', price:4500,  discount:15, image:'Images/Casual%20Dresses/1111_0cdb5036-8897-40be-81e2-88cdb7e462a6_1.webp', colors:['#000000','#2F4F4F','#FFFFFF'], description:'Tailored blazer set that exudes power and femininity — structured yet effortlessly cool.' },
        { id:'c6',  name:'Knit Top',                    category:'Casual', price:3000,  discount:15, image:'Images/Casual%20Dresses/a5e8dae0c414b353f54923bb5d7e6ef5.jpg', colors:['#FFFFFF','#F5F5F5','#FFB6C1'], description:'Soft ribbed knit top that pairs with everything — an everyday essential elevated.' },
        { id:'c7',  name:'Chic Cotton Maxi Dress',      category:'Casual', price:4750,  discount:15, image:'Images/Casual%20Dresses/049A1500.webp', colors:['#FAF0E6','#FFE4E1','#FFFFFF'], description:'Flowing cotton maxi dress with relaxed elegance — perfect for warm-weather sophistication.' },
        { id:'c8',  name:'Pleated Midi Skirt',          category:'Casual', price:3250,  discount:15, image:'Images/Casual%20Dresses/CECILIA_1.webp', colors:['#000000','#D4AF37','#F5F5F5'], description:'Elegantly pleated midi skirt that moves beautifully — a versatile wardrobe hero.' },
        { id:'c9',  name:'Breezy Summer Shirt Dress',   category:'Casual', price:3500,  discount:15, image:'Images/Casual%20Dresses/U2167A_2_540x.webp', colors:['#ADD8E6','#FFFFFF','#F5F5DC'], description:'Effortless shirt dress in breathable cotton — your go-to for sun-kissed weekends.' },
        { id:'c10', name:'Ribbed Knit Co-Ord',           category:'Casual', price:3750,  discount:15, image:'Images/Casual%20Dresses/gulahmed-ideas-blue-3-piece-unstitched-lawn-suit-new-season-2025.webp', colors:['#FFB6C1','#FFFFFF','#000000'], description:'Cozy ribbed knit co-ord set that blends comfort with street-style edge.' },
        { id:'c11', name:'Denim Button-Up Top',          category:'Casual', price:3000,  discount:15, image:'Images/Casual%20Dresses/images%20(9).jpeg', colors:['#4169E1','#FFFFFF','#D3D3D3'], description:'Classic denim button-up reimagined with modern cuts — casual cool perfected.' },
        { id:'c12', name:'Wrap Tie Top & Skirt',          category:'Casual', price:4000,  discount:15, image:'Images/Casual%20Dresses/images%20(10).jpeg', colors:['#000000','#FFFFFF','#D4AF37'], description:'Flattering wrap tie top paired with a flowing skirt — feminine charm in every detail.' }
    ],

    abaya: [
        { id:'a1',  name:'Silk Velvet Abaya',              category:'Abaya', price:8500,  discount:10, image:'Images/Abbaya/bb.jpg', colors:['#000000','#1A1A1A','#0A0A0A'], description:'Luxurious silk velvet abaya that blends timeless tradition with modern luxury — perfected for special occasions.' },
        { id:'a2',  name:'Embroidered Modest Abaya',       category:'Abaya', price:8900,  discount:10, image:'Images/Abbaya/88C0E472-AD9D-4DA7-838F-E0D60D8DFBD3_600x.webp', colors:['#000000','#2F1B12','#3B2F2F'], description:'Hand-embroidered modest abaya with intricate detailing — elegant refinement for every occasion.' },
        { id:'a3',  name:'Chiffon Layered Abaya',          category:'Abaya', price:9300,  discount:10, image:'Images/Abbaya/c.jpg', colors:['#000000','#1A1A1A','#2F2F2F'], description:'Flowing chiffon layered abaya with graceful movement — modesty meets modern sophistication.' },
        { id:'a4',  name:'Ivory Modest Gown',              category:'Abaya', price:9700,  discount:10, image:'Images/Abbaya/11_Websize_1.jpg', colors:['#FFFFF0','#FAF0E6','#F5F5DC'], description:'Pristine ivory modest gown with clean lines and premium finishing — understated luxury.' },
        { id:'a5',  name:'Luxe Crepe Abaya',               category:'Abaya', price:8500,  discount:10, image:'Images/Abbaya/HeZgspRH3epAJQKXmBlJ5SC7TSM6VkTCekvdAxvo.webp', colors:['#000000','#1A1A1A','#0A0A0A'], description:'Premium crepe abaya with fluid drape and impeccable tailoring — daily elegance perfected.' },
        { id:'a6',  name:'Satin Lined Everyday Abaya',     category:'Abaya', price:8000,  discount:10, image:'Images/Abbaya/b.jpg', colors:['#000000','#2F2F2F','#3B2F2F'], description:'Everyday abaya with luxurious satin lining — comfort and elegance for daily wear.' },
        { id:'a7',  name:'Pearl Trim Open Abaya',          category:'Abaya', price:9500,  discount:10, image:'Images/Abbaya/abb.jpg', colors:['#000000','#1A1A1A','#F5F5DC'], description:'Open-front abaya with delicate pearl trim — a touch of opulence for special gatherings.' },
        { id:'a8',  name:'Pinstripe Tailored Abaya',       category:'Abaya', price:8700,  discount:10, image:'Images/Abbaya/abbaya.jpg', colors:['#000000','#1A1A1A','#2F4F4F'], description:'Tailored pinstripe abaya with a structured silhouette — modern modest fashion at its finest.' },
        { id:'a9',  name:'Linen Relaxed Abaya',            category:'Abaya', price:8200,  discount:10, image:'Images/Abbaya/a.jpg', colors:['#000000','#2F1B12','#3B2F2F'], description:'Relaxed-fit linen abaya for breezy comfort — effortless modesty in premium fabric.' },
        { id:'a10', name:'Kimono Style Abaya',             category:'Abaya', price:9000,  discount:10, image:'Images/Abbaya/8.jpg', colors:['#000000','#800000','#1A1A1A'], description:'Kimono-inspired abaya with wide sleeves and a wrapped silhouette — cultural fusion perfected.' },
        { id:'a11', name:'Lace Trim Evening Abaya',        category:'Abaya', price:9800,  discount:10, image:'Images/Abbaya/images%20(1).jpeg', colors:['#000000','#1A1A1A','#0A0A0A'], description:'Evening abaya with delicate lace trim — refined elegance for moonlit gatherings.' },
        { id:'a12', name:'Minimalist Nude Abaya',          category:'Abaya', price:8400,  discount:10, image:'Images/Abbaya/images%20(2).jpeg', colors:['#D2B48C','#C4A882','#000000'], description:'Minimalist nude abaya with clean lines — understated luxury for the modern woman.' }
    ],

    bags: [
        { id:'bg1', name:'Quilted Chain Handbag',           category:'Bags', price:4500,  discount:5,  image:'Images/bag/51kYPiHgw9L._AC_UF350,350_QL80_.jpg', colors:['#D4AF37','#000000','#F8F8F8'], description:'A quilted chain handbag — a statement piece crafted with precision and an unmistakable touch of opulence.' },
        { id:'bg2', name:'Sleek Leather Tote',              category:'Bags', price:4800,  discount:5,  image:'Images/bag/71q39btMbyL._AC_SX679_.jpg', colors:['#8B4513','#A0522D','#000000'], description:'Sleek leather tote with spacious interior — practical luxury for the modern woman on the go.' },
        { id:'bg3', name:'Silk Evening Pouch',              category:'Bags', price:5100,  discount:5,  image:'Images/bag/9998CREAM_1_e0faa74f-3319-4cb5-af3e-d69658fc7a48.webp', colors:['#C0C0C0','#D4AF37','#000000'], description:'Silk evening pouch with satin finish — the perfect companion for cocktail affairs.' },
        { id:'bg4', name:'Mini Structured Bag',             category:'Bags', price:4200,  discount:5,  image:'Images/bag/b8c363e6443b06882d6afcd5e621b4a7.jpg', colors:['#000000','#FFFFFF','#D4AF37'], description:'Mini structured bag with clean geometry — compact luxury that makes a bold statement.' },
        { id:'bg5', name:'Pearl Clutch Bag',                category:'Bags', price:5500,  discount:5,  image:'Images/bag/c12ed6f0a312d808228b3bceef6af0cd.jpg_720x720q80.jpg', colors:['#FFFFFF','#F5F5DC','#FFE4E1'], description:'Pearl-encrusted clutch bag — a show-stopping piece for your most glamorous evenings.' },
        { id:'bg6', name:'Bamboo Handle Shoulder Bag',      category:'Bags', price:4700,  discount:5,  image:'Images/bag/3759011a9c0851a24dc31ca638f20d11.jpg', colors:['#D2B48C','#8B4513','#000000'], description:'Bamboo handle shoulder bag blending natural charm with designer aesthetics.' },
        { id:'bg7', name:'Satin Bow Evening Bag',           category:'Bags', price:5300,  discount:5,  image:'Images/bag/2024-Fashion-Ladies-Shoulder-Bags-Set-Latest-Design-Trendy-Newest-Female-Bags-Women-s-Luxury-Handbags-for-Ladies.avif', colors:['#FFB6C1','#FFFFFF','#D4AF37'], description:'Satin bow evening bag — feminine glamour wrapped in luxurious fabric and delicate details.' },
        { id:'bg8', name:'Woven Straw Summer Bag',          category:'Bags', price:3800,  discount:5,  image:'Images/bag/2025-Newest-Wholesale-Fashion-Bags-Ladies-Elegance-Purse-Cheap-Wholesale-Women-s-Purses-and-Handbags.jpg_300x300.avif', colors:['#D2B48C','#F5DEB3','#000000'], description:'Woven straw summer bag — breezy beach-ready style with artisanal craftsmanship.' },
        { id:'bg9', name:'Classic Flap Shoulder Bag',       category:'Bags', price:5800,  discount:5,  image:'Images/bag/I-0314-Ladies-Handbags-Wholesale-Turkey-Handbag-Famous-Brand-Designer-High-Volume-Luxury-Handbag-for-Women.jpg_300x300.avif', colors:['#000000','#D4AF37','#8B4513'], description:'Classic flap shoulder bag — timeless design that elevates every outfit instantly.' },
        { id:'bg10',name:'Chain Strap Sling Bag',           category:'Bags', price:4000,  discount:5,  image:'Images/bag/New-Trendy-Fashion-Ladies-Clutch-Purse-Soft-PU-Leather-Large-Capacity-Simple-Design-Handbags.avif', colors:['#C0C0C0','#000000','#FFFFFF'], description:'Chain strap sling bag — hands-free luxury with a polished edge for city adventures.' },
        { id:'bg11',name:'Velvet Evening Clutch',           category:'Bags', price:5200,  discount:5,  image:'Images/bag/images%20(1).jpeg', colors:['#800000','#000000','#D4AF37'], description:'Velvet evening clutch in rich jewel tones — opulence you can hold in your hand.' },
        { id:'bg12',name:'Gold Detail Handbag',             category:'Bags', price:4900,  discount:5,  image:'Images/bag/images%20(2).jpeg', colors:['#D4AF37','#000000','#FFFFFF'], description:'Gold detail handbag with premium hardware — where luxury meets everyday functionality.' }
    ],

    shoes: [
        { id:'s1',  name:'Crystal Heeled Sandals',          category:'Shoes', price:6500,  discount:0,  image:'Images/Shoes/White_Purple_Block_Heel_Sandal_PIU_168-3.webp', colors:['#FFFFFF','#000000','#D4AF37'], description:'Step into luxury with crystal heeled sandals — hand-finished footwear engineered for style without compromising comfort.' },
        { id:'s2',  name:'Nude Slingback Heels',            category:'Shoes', price:6900,  discount:0,  image:'Images/Shoes/59f40ccfa891754b89561111b918c2d9.jpg', colors:['#D2B48C','#FFB6C1','#000000'], description:'Nude slingback heels with a flattering silhouette — elongate your legs in refined elegance.' },
        { id:'s3',  name:'White Block Heels',               category:'Shoes', price:7300,  discount:0,  image:'Images/Shoes/c0a8eaca8e0ea3f31247db267fb15be4.jpg', colors:['#FFFFFF','#F5F5F5','#000000'], description:'White block heels — the perfect balance of style and stability for all-day wear.' },
        { id:'s4',  name:'Gold Statement Heels',            category:'Shoes', price:7700,  discount:0,  image:'Images/Shoes/41B3rQ+F1cS._AC_UF1000,1000_QL80_.jpg', colors:['#D4AF37','#FFD700','#000000'], description:'Gold statement heels that demand attention — metallic glamour for your most impactful entrances.' },
        { id:'s5',  name:'Classic Ballet Flats',            category:'Shoes', price:5500,  discount:0,  image:'Images/Shoes/51KlR28AwOL._AC_UF1000,1000_QL80_.jpg', colors:['#000000','#FFB6C1','#FFFFFF'], description:'Classic ballet flats — timeless comfort meets Parisian chic for every occasion.' },
        { id:'s6',  name:'Strappy Stiletto Heels',         category:'Shoes', price:7500,  discount:0,  image:'Images/Shoes/71-n2HJ73aL._AC_UF1000,1000_QL80_.jpg', colors:['#000000','#D4AF37','#FFB6C1'], description:'Strappy stiletto heels — bold, architectural, and unapologetically glamorous.' },
        { id:'s7',  name:'Pearl Embellished Pumps',         category:'Shoes', price:8000,  discount:0,  image:'Images/Shoes/30ce8a0ecc6a6edba11422cc81a9be05.jpg_720x720q80.jpg', colors:['#FFFFFF','#F5F5DC','#FFB6C1'], description:'Pearl embellished pumps — where classic meets couture in every careful detail.' },
        { id:'s8',  name:'Suede Ankle Boots',               category:'Shoes', price:7200,  discount:0,  image:'Images/Shoes/uexmw_512.webp', colors:['#8B4513','#000000','#D2B48C'], description:'Suede ankle boots with premium finish — autumn luxury for the style-conscious.' },
        { id:'s9',  name:'Bridal Ivory Pumps',              category:'Shoes', price:8500,  discount:0,  image:'Images/Shoes/1_6bf6fddb-2cd0-40d9-b382-3f868f3df482.webp', colors:['#FFFFFF','#FFFFF0','#F5F5DC'], description:'Bridal ivory pumps — the perfect finishing touch for your walk down the aisle.' },
        { id:'s10', name:'Transparent Strap Heels',         category:'Shoes', price:6800,  discount:0,  image:'Images/Shoes/t843-5_1757434103-736117780962.jpg', colors:['#FFFFFF','#F5F5F5','#E8E8E8'], description:'Transparent strap heels — modern minimalism that lets your outfit do the talking.' },
        { id:'s11', name:'Satin Evening Heels',             category:'Shoes', price:7800,  discount:0,  image:'Images/Shoes/0f6cd81ea4d06f54a5e938bc2aa04395.jpg_960x960q80.jpg_.webp', colors:['#FFB6C1','#FFFFFF','#D4AF37'], description:'Satin evening heels with a luminous sheen — red-carpet ready in every step.' },
        { id:'s12', name:'Platform Block Heels',            category:'Shoes', price:7000,  discount:0,  image:'Images/Shoes/2024-Top-Fashion-Luxury-Women-Female-Sandals-Shoe-Elegance-Comfort-Lady-Sandal-Shoes-Woman-Female-Summer-Footwear.avif', colors:['#000000','#FFFFFF','#D4AF37'], description:'Platform block heels — height and comfort united in a bold, contemporary design.' }
    ],

    kids: [
        { id:'k1',  name:'Little Princess Gown',            category:'Kids', price:4500,  discount:10, image:'Images/kids/Kids-Chiffon-Frock-_-9777-Sha-Posh-Textile-232309636.webp', colors:['#F8C8DC','#FFFFFF','#6A0DAD'], description:'Charming princess gown for the little royals — because impeccable style has no age limit.' },
        { id:'k2',  name:'Junior Floral Suit',              category:'Kids', price:4750,  discount:10, image:'Images/kids/2_ab0ee29f-f7f7-4d51-a450-4a8d3cc84ae5_900x.webp', colors:['#FFE4B5','#FFF5EE','#D3D3D3'], description:'Adorable floral suit for young fashionistas — mini style with maxi charm.' },
        { id:'k3',  name:'Petite Party Dress',              category:'Kids', price:5000,  discount:10, image:'Images/kids/33_38cdb0d5-e7a1-4401-b598-86c28a7b53a0.webp', colors:['#F8C8DC','#FFB6C1','#FFFFFF'], description:'Petite party dress with sparkle details — your little one will steal the spotlight.' },
        { id:'k4',  name:'Mini Frill Dress',                category:'Kids', price:4250,  discount:10, image:'Images/kids/998034c77d14d98d000891b84f656525.jpg', colors:['#FFB6C1','#FFFFFF','#F8C8DC'], description:'Sweet frill dress with layers of fun — playful elegance for everyday adventures.' },
        { id:'k5',  name:'Royal Playdate Dress',            category:'Kids', price:5250,  discount:10, image:'Images/kids/745131a397920985e31509ccaa6bc70e.jpg', colors:['#800000','#D4AF37','#FFFFFF'], description:'Royal-inspired playdate dress — little girls deserve grand fashion moments.' },
        { id:'k6',  name:'Tulle Tutu Party Dress',          category:'Kids', price:4500,  discount:10, image:'Images/kids/6f76d0de0e4f2477850d5ae935daa8e3.jpg_720x720q80.jpg', colors:['#FFB6C1','#FFFFFF','#F8C8DC'], description:'Tulle tutu party dress — twirl-worthy magic for celebrations and photoshoots.' },
        { id:'k7',  name:'Bow Detail Chiffon Dress',        category:'Kids', price:4750,  discount:10, image:'Images/kids/7mxeb_512.webp', colors:['#F8C8DC','#FFFFFF','#FFB6C1'], description:'Chiffon dress with adorable bow details — sweet sophistication for little ladies.' },
        { id:'k8',  name:'Junior Embroidery Suit',          category:'Kids', price:5500,  discount:10, image:'Images/kids/Kids-Dresses-2023-Summer-new-sequin-Beaded-teens-beauty-pageant-Baby-Princess-long-dress-Girls-dress.jpg_640x640Q90.jpg_.avif', colors:['#000000','#D4AF37','#FFFFFF'], description:'Junior embroidery suit — hand-crafted details for the youngest trendsetters.' },
        { id:'k9',  name:'Little Blush Frock',              category:'Kids', price:4000,  discount:10, image:'Images/kids/Rewenti-Kids-Dress-Girls-Sleeveless-Princess-Dress-Bow-Tie-Lace-Flowers-Mesh-Dress-Tufted-Dress-Hot-Pink-9-10-Years_69c8776c-714b-4864-b72d-ddebe930b944.4070b409c190591d74e6723798bbb8b0.avif', colors:['#FFB6C1','#FFE4E1','#FFFFFF'], description:'Little blush frock in soft tones — gentle elegance for your precious one.' },
        { id:'k10', name:'Sparkle Sequin Dress',            category:'Kids', price:5250,  discount:10, image:'Images/kids/bbcbf6079de2c894b75cefd72c3f434e.jpg', colors:['#C0C0C0','#FFB6C1','#FFFFFF'], description:'Sparkle sequin dress that shines bright — for the little star who loves to dazzle.' },
        { id:'k11', name:'Baby Pink Casual Set',            category:'Kids', price:3750,  discount:10, image:'Images/kids/bb0ad35ae4d6e8406861a7ffbc9755a2.jpg', colors:['#FFB6C1','#FFFFFF','#F8C8DC'], description:'Baby pink casual set — comfort meets cuteness for daily adventures.' },
        { id:'k12', name:'Flower Girl Gown',                category:'Kids', price:5000,  discount:10, image:'Images/kids/images%20(1).jpeg', colors:['#FFFFFF','#F8C8DC','#FFB6C1'], description:'Flower girl gown with petal-inspired details — a scene-stealer at any wedding.' }
    ]
};

window.productsData = productsData;